name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v2.1.0
      - run: dotnet test
